list_lru: fix FaultError in slab_object_to_memcgidx
======================================================================
ERROR: test_list_lru (tests.test_list_lru.TestListLru.test_list_lru)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/test/tests/test_list_lru.py", line 157, in test_list_lru
    do_test_list_lru(self.prog)
  File "/root/test/tests/test_list_lru.py", line 119, in do_test_list_lru
    memcg = slab_object_to_memcgidx(bp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/test/drgn_tools/list_lru.py", line 283, in slab_object_to_memcgidx
    if memcg:
       ^^^^^
_drgn.FaultError: address is not mapped: 0x10
Stdout:
memcg aware test on / dentry lru at 0xffff8a0f402ccc70
0 dentrys found successfully
memcg aware test on / dentry lru at 0xffff8a0f4aea6c70
100 dentrys found successfully
memcg unaware test on / xfs_buf lru at 0xffff8a0f4aea6c70
----------------------------------------------------------------------

This slab had a "slabobj_ext" but the "objcg" pointer is NULL. The
result is that, accessing the "memcg" field at offset 0x10, we get a
FaultError. The solution is to check objcg before dereferencing.

Orabug: 39653070

Signed-off-by: Stephen Brennan <stephen.s.brennan@oracle.com>