debuginfo: cache "using_ctf" so we know module debuginfo is loaded
For module debuginfo, we use a heuristic to detect whether debuginfo is
loaded. This can fail and it's also extra overhead. When we load CTF, we
know that we've got debuginfo for all modules. Cache this fact and use
it to special case the module_has_debuginfo() check.

This fixes test failures which happen due to a failed check. The test
failures result in rather cryptic errors due to missing type fields. EG:

    AttributeError: 'struct files_struct' has no member 'fdt'

These get caused because when CTF is loaded, the failed check will
result in the debuginfo code loading a DWARF module debuginfo file,
which can cause conflicts in the type lookups.

Signed-off-by: Stephen Brennan <stephen.s.brennan@oracle.com>