pstack: drop task_on_cpu() helper
This was introduced in drgn 0.0.33. For UEK it's doing nothing more than
"cpu_curr(prog, task_cpu(task)) == task". So open-code it instead. This
fixes errors like:

ImportError: cannot import name 'task_on_cpu' from 'drgn.helpers.linux' (/usr/lib64/python3.9/site-packages/drgn/helpers/linux/__init__.py)

Signed-off-by: Stephen Brennan <stephen.s.brennan@oracle.com>