rds: don't operate for rds_tcp
The current code implicitly assumes that the system is using rds_rdma.
If the module runs on a system with rds_tcp loaded, we get a traceback
ending in the following error:

  KeyError: 'rds_ib_devices'

I don't know whether rds_tcp support is desired at this time, but at a
minimum, corelens should not throw a traceback. So, explicitly require
rds_rdma for this module. Now, for rds_tcp, we get the following
standard corelens warning that explains the situation.

  warning: rds skipped because 'rds, rds_rdma' was (were) not (all) loaded in the kernel

Orabug: 37894843

Signed-off-by: Stephen Brennan <stephen.s.brennan@oracle.com>